galleria/galleria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from authy.views import UserProfile, follow

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('user/', include('authy.urls')),
    path('direct/', include('direct.urls')),
    path('notifications/', include('notifications.urls')),
    path('<username>/', UserProfile, name='profile'),
    path('<username>/saved', UserProfile, name='profilefavorites'),
    path('<username>/follow/<option>', follow, name='follow'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

galleria/notifications/urls.py
from django.urls import path
from notifications.views import ShowNotifications, DeleteNotification

urlpatterns = [
    path('', ShowNotifications, name='show-notifications'),
    path('<noti_id>/delete', DeleteNotification, name='delete-notification'),
]

galleria/post/urls.py
from post.views import index, NewPost, PostDetails, tags, search, like, favorite, deletepost
from django.urls import path

urlpatterns = [
    path('', index, name='index'),
    path('newpost/', NewPost, name='newpost'),
    path('<uuid:post_id>', PostDetails, name='postdetails'),
    path('<uuid:post_id>/like', like, name='postlike'),
    path('<uuid:post_id>/favorite', favorite, name='postfavorite'),
    path('<uuid:post_id>/deletepost', deletepost, name='deletepost'),
    path('tags/<slug:tag_slug>', tags, name='tags'),
    path('search/', search, name='search'),
    
    
]

galleria/notifications/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Notification(models.Model):
    NOTIFICATION_TYPES = ((1, 'Like'), (2, 'Comment'), (3, 'Follow'))
    
    post = models.ForeignKey('post.Post', on_delete=models.CASCADE, related_name="noti_post", blank=True, null=True)
    sender = models.ForeignKey(User, related_name="noti_from_user", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="noti_to_user", on_delete=models.CASCADE)
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
    text_preview = models.CharField(max_length=90, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

galleria/authy/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from authy.models import Profile
from authy.validator import validate_email



def ForbiddenUsers(value):
    forbidden_users = ['admin', 'css', 'js', 'authenticate', 'login', 'logout', 'administrator', 'root',
                       'email', 'user', 'join', 'sql', 'static', 'python', 'delete']
    if value.lower() in forbidden_users:
        raise ValidationError(
            'Invalid name for user, this is a reserverd word.')


def InvalidUser(value):
    if '@' in value or '+' in value or '-' in value:
        raise ValidationError(
            'This is an Invalid user, Do not user these chars: @ , - , + ')


def UniqueEmail(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError('User with this email already exists.')


def UniqueUser(value):
    if User.objects.filter(username__iexact=value).exists():
        raise ValidationError('User with this username already exists.')


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(validators = [validate_email])

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class SignupForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(), max_length=30, required=True,)
    email = forms.CharField(widget=forms.EmailInput(),
                            max_length=100, required=True,)
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(), required=True, label="Confirm your password.")

    class Meta:

        model = User
        fields = ('username', 'email', 'password')

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].validators.append(ForbiddenUsers)
        self.fields['username'].validators.append(InvalidUser)
        self.fields['username'].validators.append(UniqueUser)
        self.fields['email'].validators.append(UniqueEmail)

    def clean(self):
        super(SignupForm, self).clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password != confirm_password:
            self._errors['password'] = self.error_class(
                ['Passwords do not match. Try again'])
        return self.cleaned_data


class ChangePasswordForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(
        widget=forms.PasswordInput(), label="Old password", required=True)
    new_password = forms.CharField(
        widget=forms.PasswordInput(), label="New password", required=True)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(), label="Confirm new password", required=True)

    class Meta:
        model = User
        fields = ('id', 'old_password', 'new_password', 'confirm_password')

    def clean(self):
        super(ChangePasswordForm, self).clean()
        id = self.cleaned_data.get('id')
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            self._errors['old_password'] = self.error_class(
                ['Old password do not match.'])
        if new_password != confirm_password:
            self._errors['new_password'] = self.error_class(
                ['Passwords do not match.'])
        return self.cleaned_data


class EditProfileForm(forms.ModelForm):
    picture = forms.ImageField(required=False)
    first_name = forms.CharField(
        widget=forms.TextInput(), max_length=50, required=False)
    last_name = forms.CharField(
        widget=forms.TextInput(), max_length=50, required=False)
    location = forms.CharField(
        widget=forms.TextInput(), max_length=25, required=False)
    email = forms.CharField(
        widget=forms.TextInput(), max_length=260, required=False)
    profile_info = forms.CharField(
        widget=forms.TextInput(), max_length=260, required=False)

    class Meta:
        model = Profile
        fields = ('picture', 'first_name', 'last_name',
                  'location', 'email', 'profile_info')

galleria/comment/forms.py
from django import forms
from comment.models import Comment

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'input is-medium'}), required=True)
    
    class Meta:
        model = Comment
        fields = ('body',)

galleria/notifications/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse

from notifications.models import Notification

# Create your views here.

def ShowNotifications(request):
    user = request.user
    notifications = Notification.objects.filter(user=user).order_by('-date')
    Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)
    
    template = loader.get_template('notifications.html')
    
    context = {
        'notifications': notifications,
    }
    
    return HttpResponse(template.render(context, request))


def DeleteNotification(request, noti_id):
    user = request.user
    Notification.objects.filter(id=noti_id, user=user).delete()
    return redirect('show-notifications')

def CountNotifications(request):
    count_notifications = 0
    if request.user.is_authenticated:
        count_notifications = Notification.objects.filter(user=request.user, is_seen=False).count()
        
    return {'count_notifications': count_notifications}

galleria/galleria/templates/change_password.html
{% extends 'base.html' %}
{% load static %}

        
{% block content %}

<div class="row center-align">
    <form method="post" action="" role="form" class="col s12">
    </h3>
      <div class="row">
        {% csrf_token %}
        {{ form.id }}
        <h3>Change password</h3>
        <div class="input-field col s12">
          {{ form.old_password }}
          <label for="old_password">Old password</label>
        </div>
      </div>
        <div class="row">
        <div class="input-field col s12">
          {{ form.new_password }}
          <label for="new_password">New password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          {{ form.confirm_password }}
          <label for="password">Re-type password</label>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
        </div>
      </div>
      <button class="btn waves-effect waves-light" type="submit" name="action"><i class="material-icons left">send</i>Change Password</button>
    </form>
  </div>

{% endblock %}

galleria/galleria/templates/change_password_done.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	<br>
	<br>
	<br>
	<br>
	<div class="col s12 center-align">
		<i class="large material-icons green-text">check_circle</i>
	</div>
	<div class="col s12 center-align">
		<h4>Your password has been succesfully changed</h4>
	</div>


</div>

<br>
<br>
{% endblock %}

galleria/galleria/templates/deletepost.html
{% extends 'base.html' %} 

{% load static %}

{% block content %}







































      <div class="feeds-content dark-mode-2">
        <div class="feeds-header dark-mode-1">
          <div class="header-top border">
          <form method="POST">
          {% csrf_token %}
            <h4 style="margin-left: 5rem" class="light-text">Do you really want to delete this?</h4>
            <button>Delete</button>

          </div>
          
      
       
          <div class="header-post dark-mode-1 border">


          






  
            
 

          </div>
        </div>


        

        






  

    





{% endblock %}

galleria/galleria/templates/edit_profile.html
{% extends 'base.html' %} 

{% load static %}

{% block content %}






































feeds content
      <div class="feeds-content dark-mode-2">
        <div class="feeds-header dark-mode-1">
          <div class="header-top border">
            <h4 style="margin-left: 5rem" class="light-text">Upload a post</h4>
          </div>
          
      
       
          <div class="header-post dark-mode-1 border">


          






  
            <form method="post" action="" enctype="multipart/form-data" role="form">
               {% csrf_token %}
        <div class="posts dark-mode-1">
        
         <div class="upload-picture">
        <h2>Image:</h2>
         <i class="fas fa-image fa-w-14 fa-2x"></i>
          <input type="file" name="picture" id="id_picture" class="custom-file-input">
             <button type="submit" name="action" class="upload-btn">
             <i class="fas fa-user-edit"></i>&nbsp;<h4> Update</h4>
          </button>
       </div>
     

        <div class="upload-tag">
           <input type="text" name="first_name" id="id_first_name" placeholder="First Name"  class="dark-mode-2 light-text border" />
        </div> 

         <div class="upload-tag">
          <input type="text" name="last_name" id="id_last_name" placeholder="Last Name"  class="dark-mode-2 light-text border" />
        </div> 

         <div class="upload-tag">
          <input type="text" name="location" id="id_location" placeholder="Your Airbnb Location"  class="dark-mode-2 light-text border" />        </div> 

         <div class="upload-tag">
           <input type="text" name="email" id="id_email" placeholder="Your Airbnb email"  class="dark-mode-2 light-text border" />
        </div> 

        
  
            <div class="caption">         
            
           <textarea
            class="dark-mode-2 light-text border"
              type="text" 
              name="profile_info" 
              id="id_profile_info" 
              placeholder="Tell Airfam about yourself" 
              maxlength=1500></textarea>


        <style> 
              textarea {
                margin-top: 3rem;
                margin-left: 4.5rem;
                width: 105%;
                height: 20rem;
                padding: 12px 20px;
                box-sizing: border-box;
                border: 0.1rem  #eee;
	              border-radius: 1.5rem;
	              background-color: #d6e1e9;
                font-size: 16px;
                resize: none;
                box-shadow: 0 0.3rem 1rem rgba(0, 0, 0, 0.3);
              }
              textarea:focus{
               background-color: #fff;
               border: 0.1rem solid #00adb3;
              }
         </style>  






             
           <!--<input 
              type="text" 
              name="profile_info" 
              id="id_profile_info" 
              placeholder="Tell Airfam about your post!" 
              class="dark-mode-2 light-text border"
              />-->  






          


             
         
           

              
            </div>
            
        </div>
    </form>
 

          </div>
        </div>


        

        






  

    





{% endblock %}








     <!-- <div class="feeds-content dark-mode-2">
        <div class="feeds-header dark-mode-1">
          <div class="header-top border">
            <h4 style="margin-left: 5rem" class="light-text">Edit Profile</h4>
          </div>
          
      
       
          <div class="header-post dark-mode-1 border">
  
               <form method="post" action="" enctype="multipart/form-data" role="form">
               {% csrf_token %}
        <div class="posts dark-mode-1">
        
         <div class="upload-picture">
        <h2>Image</h2>
         <i class="fas fa-image fa-w-14 fa-2x"></i>
          <input type="file" name="picture" id="id_picture" class="custom-file-input">
            
       </div>

      

        <div class="upload-tag">
          <input type="text" name="first_name" id="id_first_name" placeholder="First Name"  class="dark-mode-2 light-text border" />
        </div>&nbsp;

          <div class="upload-tag">  
          <input type="text" name="last_name" id="id_last_name" placeholder="Last Name"  class="dark-mode-2 light-text border" />
        </div>&nbsp;
          <div class="upload-tag">   
          <input type="text" name="location" id="id_location" placeholder="Your Airbnb Location"  class="dark-mode-2 light-text border" />
        </div>&nbsp;
         <div class="upload-tag"> 
          <input type="text" name="email" id="id_email" placeholder="Your Airbnb email"  class="dark-mode-2 light-text border" />
        </div>

        
  
            <div class="caption">         
            
       
             
              <input 
              type="text" 
              name="profile_info" 
              id="id_profile_info" 
              placeholder="Tell Airfam about your post!" 
              class="dark-mode-2 light-text border"
              />






          


             
          <button type="submit" name="action" class="upload-btn">
            Upload
          </button>

              
            </div>
            
        </div>
    </form>


          </div>
        </div>

        






  

    





-->

galleria/galleria/templates/followers.html
{% extends 'base.html' %} 

{% load static %}
{% load humanize %}

{% block content %}





<!-- feeds content -->
      <div class="feeds-content dark-mode-2">



        <div  class="feeds-header dark-mode-1">
          <div class="header-top border">
            <h4 class="light-text">Notifications</h4>
          </div>
        </div>


        <div class="posts dark-mode-1">
        {% for notification in notifications %}
    



         


  


       {% if notification.notification_type == 3 %}
           <div style=" box-shadow: 0 0.3rem 1rem rgba(0, 0, 0, 0.3)" class="post border">
            <div class="user-avatar">

               {% if notification.sender.profile.picture %}
              <img src="{{ notification.sender.profile.picture.url }}" />
              {% else %}
              <img src="{% static 'images/icon.12.png' %}" />
            {% endif %}
            </div>
            <div class="post-content">
              <div class="post-user-info light-text">
               <h4>{% if notification.sender.profile.first_name %} {{ notification.sender.profile.first_name }}
                {{ notification.sender.profile.last_name }}{% endif %}</h4>
               
                
                <span>
                <a style="text-decoration: none; color: #008489" href="{% url 'profile' notification.sender.username %}" >@{{ notification.sender.username }} <i class="fas fa-user-plus"></i></a>
               
                </span>
                 
              
              </div>
               
            
            
            </div>
             
          </div>
        {% endif %}




  




 {% endfor %}






     
  



       








      </div>
      </div>

             


{% endblock %}

galleria/galleria/templates/post_detail.html
{% extends 'base.html' %} 

{% load static %}
{% load humanize %}

{% block content %}





<!-- feeds content -->
      <div class="feeds-content dark-mode-2">
        <div class="feeds-header dark-mode-1">
          <div class="header-top border">
            <h4 class="light-text">Post Details</h4>
          </div>


        <div class="posts dark-mode-1">
          <div class="post border">
            <div class="user-avatar">
                {% if post.user.profile.picture %}
                  <img src="{{ post.user.profile.picture.url }}" />
                {% else %}
                  <img src="{% static 'images/icon.12.png' %}" />
                {% endif %}
            </div>
            <div class="post-content">
              <div class="post-user-info light-text">
                <h4>{% if post.user.profile.first_name %}{{ post.user.profile.first_name }} {{ post.user.profile.last_name }}{% endif %}</h4>
                <span>
               <a style="text-decoration: none; color: #00adb3" href="{% url 'profile' post.user.username %}" > @{{ post.user.username }}</a> 
               
              
                
                
                </span>
               
              </div>
               <p class="post-text light-text">Posted:
               <time datetime="2016-1-1">
                {{ post.posted|naturaltime }}
                </time>
                  </p>
               <p class="post-text light-text">
                {% for tag in post.tags.all %}<a style="text-decoration: none; color: #00adb3;" href="{{ tag.get_absolute_url }}" >{{ tag }}</a>{% endfor %}
                </p>
              <p class="post-text light-text">
                {{ post.caption }}
              </p>






<style>

/* Slideshow container */


/* Next & previous buttons */
.prevnext{
  width: 60rem;
  height: 15rem;
  margin-top: -27rem;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: row;
  align-content: space-between;
  justify-content: space-between;
  position: absolute;
  
}

.prev, .next {
  cursor: pointer;
  top: 50%;
  color: white;
  font-weight: bold;
  font-size: 2.1rem;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  display: flex;
  justify-content: center;
  align-items: center;
  user-select: none;
  height: 54%;
  width: 9%;
  left: 50%;
  
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */


/* Number text (1/3 etc) */


.mySlides {
  width: 60rem;
	height: 37.5rem;
  margin-left: -9rem;
  
}

.mySlides img{
  width: 100%;
	height: 100%;
	object-fit: cover;
	border-radius: 1rem;
}

.mySlides video{
  width: 100%;
	height: 100%;
	object-fit: cover;
	border-radius: 1rem;

}





/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}




</style>

  


 

 
{% for cont in post.content.all %}

<div class="mySlides fade">
  

                {% if cont.file.name|slice:"-3:" == 'jpg' or cont.file.name|slice:"-3:" == 'png' or cont.file.name|slice:"-3:" == 'gif' %}

               
                <img id="myImg" src=" {{ cont.file.url }} " />

              

                
                 

        

              {% else %}  

              <video  controls="controls" preload="metadata"  >
              <source   src="{{ cont.file.url }}#t=0.5" type="video/mp4">
              </video>
           
             {% endif %} 

            
 


<div class="prevnext">
<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
<a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>

</div>
 
{% endfor %}


  


  <script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}

</script>         







               <div class="post-icons">
                <i class="fas fa-comment-dots"></i>


              {% if liked is True %}
                <a class="liked" href="{% url 'postlike' post.id %}"><i class="fas fa-heart"> {{ post.likes }} likes</i></a>
              {% else %}
                <a class="unliked"  href="{% url 'postlike' post.id %}"><i class="fas fa-heart"> {{ post.likes }} likes</i></a>
              {% endif %}


                {% if favorited is True %}
               <a class="favorited" href="{% url 'postfavorite' post.id %}"><i class="fas fa-star">saved</i></a>
              {% else %}
                <a class="unfavorited" href="{% url 'postfavorite' post.id %}"><i class="fas fa-star">save</i></a>
              {% endif %}

              {% if user.is_authenticated and user != post.user %}
                <a class="post-icons" href="{% url 'newconversation' post.user.username %}"><i class="fas fa-shopping-cart"></i></a>
              {% endif %}

                {% if user.is_authenticated and user == post.user %}
                <a class="post-icons" href="{% url 'deletepost' post.id %}"><i class="fas fa-trash-alt"></i></a>
              {% endif %}

           </div>
         </div>
         </div>


        
          <div class="header-top border">
            <h4 class="light-text">Comments:</h4>
          </div>



       <div style="overflow-y: scroll; max-height: 30rem " class="posts dark-mode-1">
        {% for comment in comments %}
          <div class="post border">
            <div class="user-avatar">

               {% if comment.user.profile.picture %}
                  <img src="{{ comment.user.profile.picture.url }}" />
                {% else %}
                  <img style="height: 100; width: 100"  src="{% static 'images/icon.12.png' %}" />
                {% endif %}
            </div>
            <div class="post-content">
              <div class="post-user-info light-text">
                <span>
               <a style="text-decoration: none; color: #008489" href="{% url 'profile' comment.user.username %}" > @{{ comment.user.username }}</a>
               
                </span>
              
              </div>
              

                <p class="post-text light-text">
                    <time datetime="2016-1-1">
                      {{ comment.date|naturaltime }}
                    </time>
                  </p>
               <p class="post-text light-text">
                {{ comment.body }}

               
              </p>
            </div>
          </div>
          {% endfor %}


          
        </div>
          
    
             

 
  <div style="height: 10rem;" class="caption"> 
   

  <div class="textarea">
  <div style="margin-top: 3rem; margin-left: 1rem" class="user-avatar">

               {% if request.user.profile.picture %}
                  <img src="{{ request.user.profile.picture.url }}" />
                {% else %}
                  <img src="{% static 'images/icon.12.png' %}" />
                {% endif %}
            </div>
  
    <form method="post" action="" role="form">
    {% csrf_token %}          
           <textarea
            class="dark-mode-2 light-text border"
              type="text" 
              name="body" 
              id="id_body" 
              placeholder="Start typing your comment....." 
              maxlength=1500></textarea>

    </div>
      <div class="comment-btn">
            <button type="submit" name="action" >
              <h4><i class="fas fa-paper-plane"></i></h4>
            </button>
        </div>

        <style> 

              .comment-btn {
                position: absolute; 
                padding: 1px 1px;
                display: flex; 
                justify-content:center; 
                align-items: center; 
                margin-left: 52rem; 
                margin-top: -4.5rem;
                

              }
              .comment-btn button{
                background-color: #008489;
                height: 3.2rem;
                width: 3.2rem;
                cursor: pointer;
                border-radius: 3rem;
                borrder: none; 
                border: 0.1rem  #eee;
                box-shadow: 0 0.3rem 1rem rgba(0, 0, 0, 0.3);
              }
              .comment-btn i{
                color: white;
              }
              textarea {
                position: relative;
                margin-top: -6rem;
                margin-left: 8rem;
                width: 80%;
                height: 9rem;
                padding: 12px 20px;
                box-sizing: border-box;
                border: 0.1rem  #eee;
	              border-radius: 1.5rem;
	              background-color: #d6e1e9;
                font-size: 16px;
                resize: none;
                box-shadow: 0 0.3rem 1rem rgba(0, 0, 0, 0.3);
              }
              textarea:focus{
               background-color: #fff;
               border: 0.1rem solid #00adb3;
              }
         </style>  
        
   
</form>
  </div>
          </div>
        </div>








{% endblock %}

galleria/galleria/templates/signup.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href=" {% static './images/icon.12.png' %} " />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'CSS/sign-up.css' %}" />
    <title>Galleria | Register</title>
  </head>
  <body>

   <!-- login page -->
    <section class="login-page">
      <!-- login page nav -->
      <nav class="login-page-nav">
       
        <ul>
        <a href="{% url 'signup' %}"><img  style="pointer: cursor; height: 3rem; width: 3rem;   " src="{% static 'images/icon.12.png' %}" /></a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
          <li class="brand">
          </li>
          <li><a href="#">About</a></li>
          <li> <a href="{% url 'login' %}">Login &nbsp; <i class="fas fa-sign-in-alt fa-w-16 fa-1x"></i></a></li>
        </ul>
      </nav>
      <!-- end of login page nav -->
      <!-- login -->
      <div class="login">
        <div class="login-content">
          <h2 style="margin-left: -3rem" >Create your profile for Galleria</h2>
          <form class="login-form" method="POST" action=""  role="form">
          {% csrf_token %}
          
          <div class="username">
          <i class="fas fa-user fa-w-14 fa-2x"></i>
          <input type="text" name="username" autofocus required id="id_username" placeholder="select username">
          </div>

          <div class="username">
          <i class="fas fa-at fa-w-14 fa-2x"></i>
          <input type="text" name="email" id="id_email" placeholder="enter your email address">
          </div>

          <div class="username">
          <i class="fas fa-key fa-w-14 fa-2x"></i>
          <input type="password" name="password1" id="id_password1" placeholder="select password">
          </div>

          <div class="username">
          <i class="fas fa-key fa-w-14 fa-2x"></i>
          <input type="password" name="password2" id="id_password2" placeholder="confirm password">
          </div>
           
      <div class="row">
        <div class="col s12">
          <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
        </div>
      </div>
            <div>
              <button type="submit" value="login" name="action" class="login-form-btn">Create Account</button>
            </div>
          </form>
        </div>
        <footer class="login-footer">
          <p>
            Already have an account?
            <a type="button"  href="{% url 'login' %}">Login here</a>
          </p>
        </footer>
      </div>
      <!-- end of login -->

      <!-- login modal -->
     
      <!-- end of login modal -->
    </section>
    <!-- end of login page -->
   <script src="{% static 'JS/script.js' %}"></script>
  </body>
</html>